src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import LMSHome, Error404
from students.views import StudentSearchView

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", LMSHome.as_view(), name='index'),
                  path("", include("core.urls")),
                  path("search/", StudentSearchView.as_view(), name="searchbar"),
                  path("students/", include("students.urls")),
                  path("teachers/", include("teachers.urls")),
                  path("groups/", include("groups.urls")),
                  path("__debug__/", include("debug_toolbar.urls")),
                  path("oauth/", include("social_django.urls", namespace="social")),
                  path('accounts/', include('phone_auth.urls', namespace="phone_auth")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = Error404.as_view()

src/core/urls.py
from django.urls import path
from core.views import (Login, Logout, Registration, PasswordsChangeView, ActivateUser, PasswordSuccessView,
                        ProfileDetailView, ProfileUpdateView)

app_name = "core"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("password/",
         PasswordsChangeView.as_view(template_name="registration/change-password.html"), name="password"),
    path("password_success/", PasswordSuccessView.as_view(), name="password_success"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/<int:pk>", ProfileDetailView.as_view(), name="profile"),
    path("profile/<int:pk>/update", ProfileUpdateView.as_view(), name="profile-update"),

]

src/groups/urls.py
from django.urls import path
from groups.views import GroupGetView, CreateGroupView, UpdateGroupView, DeleteGroupView


app_name = "groups"

urlpatterns = [
    path("", GroupGetView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

src/students/urls.py
from django.urls import path

from students.views import StudentGetView, CreateStudentView, UpdateStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path("", StudentGetView.as_view(), name="get_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import TeacherGetView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView

app_name = "teachers"

urlpatterns = [
    path("", TeacherGetView.as_view(), name="get_teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<uuid:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<uuid:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/templates/index.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>LMS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous">
    <link rel="canonical"
          href="https://getbootstrap.com/docs/5.2/examples/cover/">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static "css/cover.css" %}" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-bg-dark">

<div class="cover-container d-flex w-100 h-100 p-1 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0"><a style="color: white; text-decoration: none;"
                                               href="{% url "index" %}">LMS</a></h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link fw-bold py-1 px-0 active"
                   aria-current="page"
                   href="{% url "index" %}">Home</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'students:get_students' %}">Students</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'teachers:get_teachers' %}">Teachers</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'groups:get_groups' %}">Groups</a>

                <a href="#"
                   class="nav-link fw-bold py-1 px-5 d-block link-dark text-decoration-none"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    {% if user.avatar %}
                        <img src="{{ user.avatar }}" alt="mdo"
                             class="rounded-circle" width="32" height="32">
                    {% else %}

                        <img src="{% static "img/default_avatar.jpeg" %}" alt="mdo"
                             class="rounded-circle" width="32" height="32">
                    {% endif %}
                </a>
                {% if user.is_authenticated %}
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="#">{{ user.email|lower }}</a></li>
                        {% if user.profile.pk %}
                            <li><a class="dropdown-item" href="{% url 'core:profile' user.profile.pk %}">Profile</a>
                            </li>
                        {% endif %}
                        {% if user.is_staff %}
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin
                                page</a>
                            </li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url "core:password" %}">Change password</a>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url "core:logout" %}">Logout</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url "core:login" %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url "core:registration" %}">Registration</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url "core:password_success" %}">Reset password</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'social:begin' backend='google-oauth2' %}">Gmail</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'social:begin' backend='facebook' %}">Facebook</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'social:begin' backend='github' %}">Github</a></li>
                    </ul>
                {% endif %}

            </nav>
        </div>
    </header>

    <main class="px-3">
        {% block content %}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}" role="alert">
                            {{ message|safe }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </ul>
            {% endif %}

            <form class="form-inline" method="GET" action="{% url "searchbar" %}">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input class="form-control mr-sm-2" type="search" name="q"
                           placeholder="Search" aria-label="Search">
                    <button class="btn btn-warning" type="submit">Search</button>
                </div>
            </form>


            <div class="container text-center w-30">
                <img src="{% static "img/1.png" %}"
                     alt="no image"
                     class="img-fluid">
            </div>
        {% endblock %}
    </main>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>
</html>