src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import LMSHome, Error404
from students.views import StudentSearchView

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", LMSHome.as_view(), name='index'),
                  path("", include("core.urls")),
                  path("search/", StudentSearchView.as_view(), name="searchbar"),
                  path("students/", include("students.urls")),
                  path("teachers/", include("teachers.urls")),
                  path("groups/", include("groups.urls")),
                  path("__debug__/", include("debug_toolbar.urls")),
                  path("oauth/", include("social_django.urls", namespace="social")),
                  path('accounts/', include('phone_auth.urls', namespace="phone_auth")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = Error404.as_view()

src/core/urls.py
from django.urls import path
from core.views import (Login, Logout, Registration, PasswordsChangeView, ActivateUser, PasswordSuccessView,
                        ProfileDetailView, ProfileUpdateView)

app_name = "core"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("password/",
         PasswordsChangeView.as_view(template_name="registration/change-password.html"), name="password"),
    path("password_success/", PasswordSuccessView.as_view(), name="password_success"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/<int:pk>", ProfileDetailView.as_view(), name="profile"),
    path("profile/<int:pk>/update", ProfileUpdateView.as_view(), name="profile-update"),

]

src/students/urls.py
from django.urls import path

from students.views import StudentGetView, CreateStudentView, UpdateStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path("", StudentGetView.as_view(), name="get_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/students/models.py
from django.db import models
from django.core import validators

from faker import Faker

from core.models import Person


class Student(Person):
    grade = models.PositiveSmallIntegerField(default=0, null=True)
    resume = models.FileField(upload_to="docs", validators=[
        validators.FileExtensionValidator(["pdf", "doc", "docx"],
                                          message="Not correct file type, you can upload only - PDF or DOC files")],
                              null=True)
    group = models.ForeignKey(to="groups.Group", on_delete=models.CASCADE, related_name="students", null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email}"

    @classmethod
    def generate_instances(cls, count: int) -> None:
        faker = Faker()
        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_time_between(start_date="-25y", end_date="-18y"),
                phone_number=faker.phone_number(),
                grade=faker.random.randint(0, 100),
            )

src/students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ("first_name", "last_name", "email", "group")

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if ".ru" in email.lower():
            raise ValidationError("You can't use .ru in email")

        return email

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]
        if first_name == last_name:
            raise ValidationError("First name and last name can`t be equal")
        return cleaned_data

src/students/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (CreateView, UpdateView, DeleteView, ListView)
from django.contrib.auth.mixins import LoginRequiredMixin

from students.models import Student
from students.forms import StudentForm


class StudentGetView(LoginRequiredMixin, ListView):
    model = Student
    template_name = "students/students_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        students = Student.objects.all()
        context["students"] = students
        return context


class CreateStudentView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentForm
    template_name = "students/students_create.html"
    success_url = reverse_lazy("students:get_students")


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentForm
    template_name = "students/students_update.html"
    success_url = reverse_lazy("students:get_students")


class DeleteStudentView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy("students:get_students")

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Student, pk=self.request.POST.get("pk"))


class StudentSearchView(LoginRequiredMixin, ListView):
    model = Student
    template_name = "tools/searchbar.html"

    def get_queryset(self):
        q = self.request.GET.get("q")
        object_list = Student.objects.filter(Q(first_name__icontains=q) | Q(last_name__icontains=q))
        return object_list

src/templates/students/students_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/students/students_list.html
{% extends "index.html" %}
{% load static %}
{% block content %}
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Group</th>
            <th scope="col">Grade</th>
            <th scope="col">Resume</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for student in students %}
            <tr>
                {% if person.avatar %}
                    <th scope="row"><img height="50" width="50" src="{{ person.avatar.url }}"
                                         alt="no image" title="avatar">
                        {% else %}
                    <th scope="row"><img height="50" width="50" src="{% static "img/default_avatar.jpeg" %}"
                                         alt="no image" title="avatar">
                {% endif %}
                </th>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                {% if student.birth_date %}
                    <td>{{ student.birth_date }}</td>
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Undefined</td>
                    <td>Undefined</td>
                {% endif %}
                <td>{{ student.group }}</td>
                <td>{{ student.grade }}</td>
                <td>{{ student.resume }}</td>
                <td><a type="button" class="btn btn-warning"
                       href="{% url 'students:update_student' student.pk %}">Edit</a>
                <td>
                    <button class="btn btn-danger" onclick="delete_item({{ student.pk }});">Delete</button>
                </td>
                <form method="post" action="{% url 'students:delete_student' student.pk %}" id="delete_form">
                    {% csrf_token %}
                    <input type="hidden" name="pk" id="delete_pk">
                </form>

                <script>
                    function delete_item(pk) {
                        var hidden_item = document.getElementById("delete_pk");
                        hidden_item.value = pk;
                        var form = document.getElementById("delete_form");
                        form.submit();
                    }
                </script>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/students/students_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update
            </button>
        </form>
    </div>
{% endblock content %}