src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import LMSHome, Error404
from students.views import StudentSearchView

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", LMSHome.as_view(), name='index'),
                  path("", include("core.urls")),
                  path("search/", StudentSearchView.as_view(), name="searchbar"),
                  path("students/", include("students.urls")),
                  path("teachers/", include("teachers.urls")),
                  path("groups/", include("groups.urls")),
                  path("__debug__/", include("debug_toolbar.urls")),
                  path("oauth/", include("social_django.urls", namespace="social")),
                  path('accounts/', include('phone_auth.urls', namespace="phone_auth")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = Error404.as_view()

src/core/urls.py
from django.urls import path
from core.views import (Login, Logout, Registration, PasswordsChangeView, ActivateUser, PasswordSuccessView,
                        ProfileDetailView, ProfileUpdateView)

app_name = "core"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("password/",
         PasswordsChangeView.as_view(template_name="registration/change-password.html"), name="password"),
    path("password_success/", PasswordSuccessView.as_view(), name="password_success"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/<int:pk>", ProfileDetailView.as_view(), name="profile"),
    path("profile/<int:pk>/update", ProfileUpdateView.as_view(), name="profile-update"),

]

src/groups/urls.py
from django.urls import path
from groups.views import GroupGetView, CreateGroupView, UpdateGroupView, DeleteGroupView


app_name = "groups"

urlpatterns = [
    path("", GroupGetView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import TeacherGetView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView

app_name = "teachers"

urlpatterns = [
    path("", TeacherGetView.as_view(), name="get_teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<uuid:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<uuid:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/teachers/models.py
from django.db import models

from faker import Faker

from core.models import Person


class Teacher(Person):
    group = models.ManyToManyField("groups.Group")

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email}"

    @classmethod
    def generate_instance(cls, count: int) -> None:
        faker = Faker()

        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                phone_number=faker.phone_number(),
                birth_date=faker.date_time_between(start_date="-60y", end_date="-30y"),
            )

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ("first_name", "last_name", "email")

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if ".ru" in email.lower():
            raise ValidationError("You can't use .ru in email")

        return email

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]
        if first_name == last_name:
            raise ValidationError("First name and last name can`t be equal")
        return cleaned_data

src/teachers/views.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import (CreateView, UpdateView, DeleteView, ListView)
from django.contrib.auth.mixins import LoginRequiredMixin

from teachers.models import Teacher
from teachers.forms import TeacherForm


class TeacherGetView(LoginRequiredMixin, ListView):
    model = Teacher
    template_name = "teachers/teachers_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teachers = Teacher.objects.all()
        context["teachers"] = teachers
        return context


class CreateTeacherView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = TeacherForm
    template_name = "teachers/teachers_create.html"
    success_url = reverse_lazy("teachers:get_teachers")


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = TeacherForm
    template_name = "teachers/teachers_update.html"
    success_url = reverse_lazy("teachers:get_teachers")


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    model = Teacher
    success_url = reverse_lazy("teachers:get_teachers")

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Teacher, pk=self.request.POST.get("pk"))

src/templates/teachers/teachers_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/teachers/teachers_list.html
{% extends "index.html" %}
{% load static %}
{% block content %}
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Group</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for teacher in teachers %}
            <tr>
                {% if person.avatar %}
                    <th scope="row"><img height="50" width="50" src="{{ person.avatar.url }}"
                                         alt="no image" title="avatar">
                        {% else %}
                    <th scope="row"><img height="50" width="50" src="{% static "img/default_avatar.jpeg" %}"
                                         alt="no image" title="avatar">
                {% endif %}
                </th>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                {% if teacher.birth_date %}
                    <td>{{ teacher.birth_date }}</td>
                    <td>{{ teacher.age }}</td>
                {% else %}
                    <td>Undefined</td>
                    <td>Undefined</td>
                {% endif %}
                <td>
                    {% for group in teacher.group.all %}
                        <a href="{% url "groups:update_group" group.pk %}">{{ group.group_name }}</a>
                    {% endfor %}
                </td>
                <td><a type="button" class="btn btn-warning"
                       href="{% url 'teachers:update_teacher' teacher.pk %}">Edit</a>
                <td>
                    <button class="btn btn-danger" onclick="delete_item({{ teacher.pk }});">Delete</button>
                </td>
                <form method="post" action="{% url 'teachers:delete_teacher' teacher.pk %}" id="delete_form">
                    {% csrf_token %}
                    <input type="hidden" name="pk" id="delete_pk">
                </form>

                <script>
                    function delete_item(pk) {
                        var hidden_item = document.getElementById("delete_pk");
                        hidden_item.value = pk;
                        var form = document.getElementById("delete_form");
                        form.submit();
                    }
                </script>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/teachers/teachers_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update
            </button>
        </form>
    </div>
{% endblock content %}