src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import LMSHome, Error404
from students.views import StudentSearchView

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", LMSHome.as_view(), name='index'),
                  path("", include("core.urls")),
                  path("search/", StudentSearchView.as_view(), name="searchbar"),
                  path("students/", include("students.urls")),
                  path("teachers/", include("teachers.urls")),
                  path("groups/", include("groups.urls")),
                  path("__debug__/", include("debug_toolbar.urls")),
                  path("oauth/", include("social_django.urls", namespace="social")),
                  path('accounts/', include('phone_auth.urls', namespace="phone_auth")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = Error404.as_view()

src/core/urls.py
from django.urls import path
from core.views import (Login, Logout, Registration, PasswordsChangeView, ActivateUser, PasswordSuccessView,
                        ProfileDetailView, ProfileUpdateView)

app_name = "core"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("password/",
         PasswordsChangeView.as_view(template_name="registration/change-password.html"), name="password"),
    path("password_success/", PasswordSuccessView.as_view(), name="password_success"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/<int:pk>", ProfileDetailView.as_view(), name="profile"),
    path("profile/<int:pk>/update", ProfileUpdateView.as_view(), name="profile-update"),

]

src/groups/urls.py
from django.urls import path
from groups.views import GroupGetView, CreateGroupView, UpdateGroupView, DeleteGroupView


app_name = "groups"

urlpatterns = [
    path("", GroupGetView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

src/groups/models.py
import random
from faker import Faker
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField


class Group(models.Model):
    group_name = models.TextField()
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    group_email = models.EmailField(max_length=100)
    group_phone = PhoneNumberField()
    amount_student = models.PositiveSmallIntegerField(default=5, null=True)
    teacher_name = models.CharField(max_length=100, null=True)
    group_number = models.IntegerField(null=True)

    def __str__(self) -> str:
        return f"{self.group_name}, {self.group_phone}, {self.group_email}"

    @classmethod
    def generate_instances(cls, count: int) -> None:
        faker = Faker()

        for _ in range(count):
            cls.objects.create(
                group_name=faker.company_suffix(),
                group_email=faker.email(),
                group_phone=faker.phone_number(),
                start_date=faker.date_time_between(start_date="-10d"),
                end_date=faker.date_time_between(start_date="-10d"),
                amount_student=random.randint(10, 15),
                teacher_name=faker.name(),
                group_number=1,

            )


class Lesson(models.Model):
    title = models.CharField(max_length=120)
    course = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True)
    position = models.IntegerField()
    video_url = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title

src/groups/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = "__all__"

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_group_name(self):
        return self.normalize_text(self.cleaned_data["group_name"])

    def clean_department_email(self):
        email = self.cleaned_data["group_email"]
        if ".ru" in email.lower():
            raise ValidationError("You can't use .ru in email")
        return email

    def clean_department_phone(self):
        department_phone = self.cleaned_data["group_phone"]
        if not department_phone.isdigit():
            raise ValidationError("Please enter a valid phone number")
        return department_phone

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import (CreateView, UpdateView, DeleteView, ListView)

from groups.models import Group
from groups.forms import GroupForm


class GroupGetView(LoginRequiredMixin, ListView):
    model = Group
    template_name = "groups/groups_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        groups = Group.objects.all()
        context["groups"] = groups
        return context


class CreateGroupView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupForm
    template_name = "groups/groups_create.html"
    success_url = reverse_lazy("groups:get_groups")


class UpdateGroupView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupForm
    template_name = "groups/groups_update.html"
    success_url = reverse_lazy("groups:get_groups")


class DeleteGroupView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('groups:get_groups')

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Group, pk=self.request.POST.get('pk'))

src/templates/groups/groups_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/groups/groups_list.html
{% extends "index.html" %}

{% block content %}
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#id</th>
            <th scope="col">Group Name</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col">Amount of Students</th>
            <th scope="col">Teacher Name</th>
            <th scope="col">Group Number</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for group in groups %}
            <tr>
                <th scope="row">{{ group.pk }}</th>
                <td>{{ group.group_name }}</td>
                <td>{{ group.start_date }}</td>
                <td>{{ group.end_date }}</td>
                <td>{{ group.group_email }}</td>
                <td>{{ group.group_phone }}</td>
                <td>{{ group.amount_student }}</td>
                <td>{{ group.teacher_name }}</td>
                {% if group.group_number %}
                    <td>{{ group.group_number }}</td>
                {% else %}
                    <td>Undefined</td>
                {% endif %}
                <td><a type="button" class="btn btn-warning"
                       href="{% url 'groups:update_group' group.pk %}">Edit</a>
                <td>
                    <button class="btn btn-danger" onclick="delete_item({{ group.pk }});">Delete</button>
                </td>
                <form method="post" action="{% url 'groups:delete_group' group.pk %}" id="delete_form">
                    {% csrf_token %}
                    <input type="hidden" name="pk" id="delete_pk">
                </form>

                <script>
                    function delete_item(pk) {
                        var hidden_item = document.getElementById("delete_pk");
                        hidden_item.value = pk;
                        var form = document.getElementById("delete_form");
                        form.submit();
                    }
                </script>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/groups/groups_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update
            </button>
        </form>
    </div>
{% endblock content %}